# Generated by Django 4.2.7 on 2025-07-12 05:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("vote_score", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_accepted", "-vote_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-is_accepted", "-vote_score"],
                        name="answers_ans_questio_cdeb1c_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="answers_ans_created_7b5bad_idx"
                    ),
                ],
            },
        ),
    ]
